



<!DOCTYPE html>
<html>
<head>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" >
 
 <meta name="ROBOTS" content="NOARCHIVE">
 
 <link rel="icon" type="image/vnd.microsoft.icon" href="https://ssl.gstatic.com/codesite/ph/images/phosting.ico">
 
 
 <script type="text/javascript">
 
 
 
 
 var codesite_token = null;
 
 
 var CS_env = {"token": null, "projectHomeUrl": "/p/goagent", "assetVersionPath": "https://ssl.gstatic.com/codesite/ph/8599073060794244502", "projectName": "goagent", "profileUrl": null, "assetHostPath": "https://ssl.gstatic.com/codesite/ph", "domainName": null, "loggedInUserEmail": null, "relativeBaseUrl": ""};
 var _gaq = _gaq || [];
 _gaq.push(
 ['siteTracker._setAccount', 'UA-18071-1'],
 ['siteTracker._trackPageview']);
 
 (function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
 
 </script>
 
 
 <title>Issue 489 - 
 goagent -
 
 Get error &quot;EOF occurred in violation of protocol&quot; - 
 https://github.com/goagent/goagent - Google Project Hosting
 </title>
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/core.css">
 
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/ph_detail.css" >
 
 
 
 
<!--[if IE]>
 <link type="text/css" rel="stylesheet" href="https://ssl.gstatic.com/codesite/ph/8599073060794244502/css/d_ie.css" >
<![endif]-->
 <style type="text/css">
 .menuIcon.off { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -42px }
 .menuIcon.on { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -28px }
 .menuIcon.down { background: no-repeat url(https://ssl.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 0; }
 
 
 .attachments { width:33%; border-top:2px solid #999; padding-top: 3px; margin-left: .7em;}
 .attachments table { margin-bottom: 0.75em; }
 .attachments table tr td { padding: 0; margin: 0; font-size: 95%; }
 .preview { border: 2px solid #c3d9ff; padding: 1px; }
 .preview:hover { border: 2px solid blue; }
 .label { white-space: nowrap; }
 .derived { font-style:italic }
 .cursor_on .author {
 background: url(https://ssl.gstatic.com/codesite/ph/images/show-arrow.gif) no-repeat 2px;
 }
 .hiddenform {
 display: none;
 }

 
 </style>
</head>
<body class="t3">
<script type="text/javascript">
 window.___gcfg = {lang: 'en'};
 (function() 
 {var po = document.createElement("script");
 po.type = "text/javascript"; po.async = true;po.src = "https://apis.google.com/js/plusone.js";
 var s = document.getElementsByTagName("script")[0];
 s.parentNode.insertBefore(po, s);
 })();
</script>
<div class="headbg">

 <div id="gaia">
 

 <span>
 
 
 <a href="#" id="projects-dropdown" onclick="return false;"><u>My favorites</u> <small>&#9660;</small></a>
 | <a href="https://www.google.com/accounts/ServiceLogin?service=code&amp;ltmpl=phosting&amp;continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489" onclick="_CS_click('/gb/ph/signin');"><u>Sign in</u></a>
 
 </span>

 </div>

 <div class="gbh" style="left: 0pt;"></div>
 <div class="gbh" style="right: 0pt;"></div>
 
 
 <div style="height: 1px"></div>
<!--[if lte IE 7]>
<div style="text-align:center;">
Your version of Internet Explorer is not supported. Try a browser that
contributes to open source, such as <a href="http://www.firefox.com">Firefox</a>,
<a href="http://www.google.com/chrome">Google Chrome</a>, or
<a href="http://code.google.com/chrome/chromeframe/">Google Chrome Frame</a>.
</div>
<![endif]-->



 <table style="padding:0px; margin: 0px 0px 10px 0px; width:100%" cellpadding="0" cellspacing="0"
 itemscope itemtype="http://schema.org/CreativeWork">
 <tr style="height: 58px;">
 
 
 
 <td id="plogo">
 <link itemprop="url" href="/p/goagent">
 <a href="/p/goagent/">
 
 <img src="https://ssl.gstatic.com/codesite/ph/images/defaultlogo.png" alt="Logo" itemprop="image">
 
 </a>
 </td>
 
 <td style="padding-left: 0.5em">
 
 <div id="pname">
 <a href="/p/goagent/"><span itemprop="name">goagent</span></a>
 </div>
 
 <div id="psum">
 <a id="project_summary_link"
 href="/p/goagent/"><span itemprop="description">https://github.com/goagent/goagent</span></a>
 
 </div>
 
 
 </td>
 <td style="white-space:nowrap;text-align:right; vertical-align:bottom;">
 
 <form action="/hosting/search">
 <input size="30" name="q" value="" type="text">
 
 <input type="submit" name="projectsearch" value="Search projects" >
 </form>
 
 </tr>
 </table>

</div>

 
<div id="mt" class="gtb"> 
 <a href="/p/goagent/" class="tab ">Project&nbsp;Home</a>
 
 
 
 
 
 
 
 
 <a href="/p/goagent/issues/list"
 class="tab active">Issues</a>
 
 
 
 
 
 
 
 
 
 
 <a href="https://code.google.com/export-to-github/export?project=goagent">
 <button>Export to GitHub</button>
 
 </a>
 
 
 
 
 
 <div class=gtbc></div>
</div>
<table cellspacing="0" cellpadding="0" width="100%" align="center" border="0" class="st">
 <tr>
 
 
 
 
 
 <td class="subt">
 <div class="issueDetail">
<div class="isf">
 
 
 <span class="inIssueEntry">
 <a class="buttonify" href="entry" onclick="return _newIssuePrompt();">New issue</a>
 </span> &nbsp;
 
 <span class="inIssueList">
 <span>Search</span>
 <form action="list" method="GET" style="display:inline">
 <select id="can" name="can">
 
<option disabled="disabled">Search within:</option>
<option value="1" >&nbsp;All issues</option>
<option value="2" selected=selected>&nbsp;Open issues</option>

<option value="6" >&nbsp;New issues</option>
<option value="7" >&nbsp;Issues to verify</option>

 </select>
 <span>for</span>
 <span id="qq"><input type="text" size="38" id="searchq" name="q"
 value="" autocomplete="off"
 
 onkeydown="_blurOnEsc(event)"></span>
 
 
 <span id="search_colspec"><input type="hidden" name="colspec" value="ID Opened Reporter Modified Summary Stars" ></span>
 
 
 
 <input type="hidden" name="cells" value="tiles" >
 <input type="submit" value="Search">
 </form>
 </span> &nbsp;
 <span class="inIssueAdvSearch">
 <a href="advsearch">Advanced search</a>
 </span> &nbsp;
 <span class="inIssueSearchTips">
 <a href="searchtips">Search tips</a>
 </span> &nbsp;
 <span class="inIssueSubscriptions">
 <a href="/p/goagent/issues/subscriptions">Subscriptions</a>
 </span>
</div>
</div>
 </td>
 
 
 
 
 <td align="right" valign="top" class="bevel-right"></td>
 </tr>
</table>


<script type="text/javascript">
 var cancelBubble = false;
 function _go(url) { document.location = url; }
</script>
<div id="maincol"
 
>

 






 

 

 

 

 

 

 


 

<div id="color_control" class="closed_colors">
<div id="issueheader">
<table cellpadding="0" cellspacing="0" width="100%"><tbody>
 <tr>
 <td class="vt h3" nowrap="nowrap" style="padding:0 5px">
 
 
 Issue <a href="detail?id=489">489</a>:
 </td>
 <td width="90%" class="vt">
 <span class="h3" >Get error &quot;EOF occurred in violation of protocol&quot;</span>
 </td>
 <td>
 
 </td>
 </tr>
 <tr>
 <td></td>
 <td nowrap="nowrap">
 
 
 4 people starred this issue and may be notified of changes.
 
 
 
 </td>
 <td align="center" nowrap="nowrap">
 
 <a href="https://code.google.com/p/goagent/issues/list?cursor=goagent%3A489">Back to list</a>
 
 </td>
 </tr>
 
</tbody></table>
</div>
<table width="100%" cellpadding="0" cellspacing="0" border="0" class="issuepage" id="meta-container">
<tbody class="collapse"> 
 <tr>
 <td id="issuemeta">
 <div id="meta-float">
 
<table cellspacing="0" cellpadding="0">
 <tr><th align="left">Status:&nbsp;</th>
 <td width="100%">
 
 <span title="Developer made source code changes, QA should verify">Fixed</span>
 
 </td>
 </tr>
 
 
 
 
 <tr><th align="left">Owner:&nbsp;</th><td>
 
 
 ----
 
 
 </td>
 </tr>
 
 
 <tr><th align="left" valign="top">Closed:&nbsp;</th>
 <td align="left" valign="top" width="100%">
 Jul 2011
 </td>
 </tr>
 
 
 <tr><td colspan="2">
 
 
 
 <div style="padding-top:2px">
 
 <a href="list?q=label:Type-Defect"
 title="Report of a software defect"
 class="label"><b>Type-</b>Defect</a>
 
 </div>
 
 
 
 
 <div style="padding-top:2px">
 
 <a href="list?q=label:Priority-Medium"
 title="Normal priority"
 class="label"><b>Priority-</b>Medium</a>
 
 </div>
 
 
 </td></tr>
 
</table>
<div class="rel_issues">
 
 
 
</div>


 <br><br>
 
 
 <div style="white-space:nowrap"><a href="https://www.google.com/accounts/ServiceLogin?service=code&amp;ltmpl=phosting&amp;continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489">Sign in</a> to add a comment</div>
 
 


 
 </div>&nbsp;
 </td>
 <td class="vt issuedescription" width="100%" id="cursorarea" >
 
<div class="cursor_off vt issuedescription" id="hc0">
 
 
 <div class="author">
 
 Reported by
 

 <a class="userlink"
 href="/u/107225113990035207381/">ufo...@gmail.com</a
>,
 <span class="date" title="Fri Jul  8 21:23:49 2011">Jul 8, 2011</span>
 
 </div>
<pre>
I use proxy.py running on Mac OS 10.6.8,anything is running good,but when I visit some pages using https,some errors occured.This is the message:



127.0.0.1:57329 - - [09/Jul/2011 12:19:50] &quot;CONNECT github.com:443 HTTP/1.1&quot; 200 -
127.0.0.1:57330 - - [09/Jul/2011 12:19:50] &quot;CONNECT d1ros97qkrwjf5.cloudfront.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:57333 - - [09/Jul/2011 12:19:50] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:57332 - - [09/Jul/2011 12:19:50] &quot;CONNECT github.com:443 HTTP/1.1&quot; 200 -
127.0.0.1:57331 - - [09/Jul/2011 12:19:50] &quot;CONNECT github.com:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
127.0.0.1:57341 - - [09/Jul/2011 12:19:50] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:57342 - - [09/Jul/2011 12:19:50] &quot;CONNECT secure.gravatar.com:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
127.0.0.1:57338 - - [09/Jul/2011 12:19:50] &quot;CONNECT secure.gravatar.com:443 HTTP/1.1&quot; 200 -
127.0.0.1:57336 - - [09/Jul/2011 12:19:50] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:57335 - - [09/Jul/2011 12:19:50] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:57337 - - [09/Jul/2011 12:19:50] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
ERROR - - [09/Jul/2011 12:19:50] do_CONNECT_GAE socket.error: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:503: EOF occurred in violation of protocol

</pre>

</div>

 


 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc1">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Fri Jul  8 21:32:24 2011">
 Jul 8, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c1" href="/p/goagent/issues/detail?id=489#c1">#1</a>
 

 <a class="userlink"
 href="/u/phus.lu/">phus.lu</a
></span>
 
<pre>
重启浏览器试下，因为你以前已经访问过了，浏览器已经缓存了原来的&quot;真正的&quot;证书，所以会拒绝goagent签发的证书。
</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc2">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Fri Jul  8 21:52:37 2011">
 Jul 8, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c2" href="/p/goagent/issues/detail?id=489#c2">#2</a>
 

 <a class="userlink"
 href="/u/107225113990035207381/">ufo...@gmail.com</a
></span>
 
<pre>
还是一样,用firefox访问错误有些不同


127.0.0.1:57997 - - [09/Jul/2011 12:46:09] &quot;CONNECT github.com:443 HTTP/1.1&quot; 200 -
127.0.0.1:57997 - - [09/Jul/2011 12:46:10] &quot;GET /phus/goagent/ HTTP/1.1&quot; 200 -
127.0.0.1:58001 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58002 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58004 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58005 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58007 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58003 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58006 - - [09/Jul/2011 12:46:10] &quot;CONNECT secure.gravatar.com:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:46:10] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:10] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:58008 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58009 - - [09/Jul/2011 12:46:10] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:46:10] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:10] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:10] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:58014 - - [09/Jul/2011 12:46:11] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58013 - - [09/Jul/2011 12:46:11] &quot;CONNECT d1ros97qkrwjf5.cloudfront.net:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:58012 - - [09/Jul/2011 12:46:11] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:58011 - - [09/Jul/2011 12:46:11] &quot;CONNECT gs1.wac.edgecastcdn.net:443 HTTP/1.1&quot; 200 -
127.0.0.1:58010 - - [09/Jul/2011 12:46:11] &quot;CONNECT ssl.google-analytics.com:443 HTTP/1.1&quot; 200 -
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
ERROR - - [09/Jul/2011 12:46:11] do_CONNECT_GAE socket.error: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
Traceback (most recent call last):
  File &quot;proxy.py&quot;, line 552, in do_CONNECT_GAE
    ssl_sock = ssl.wrap_socket(self.connection, keyFile, crtFile, True)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 372, in wrap_socket
    ciphers=ciphers)
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 134, in __init__
    self.do_handshake()
  File &quot;/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py&quot;, line 296, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:503: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
127.0.0.1:58015 - - [09/Jul/2011 12:47:10] &quot;CONNECT github.com:443 HTTP/1.1&quot; 200 -
127.0.0.1:58015 - - [09/Jul/2011 12:47:14] &quot;GET /fluidicon.png HTTP/1.1&quot; 200 -

</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc3">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Sun Jul 10 21:52:12 2011">
 Jul 10, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c3" href="/p/goagent/issues/detail?id=489#c3">#3</a>
 

 <a class="userlink"
 href="/u/phus.lu/">phus.lu</a
></span>
 
<pre>
已修复，请更新到最新版
</pre>
 
 
 <div class="updates">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 
 <b>Status:</b>
 Fixed
 
 <br>
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc4">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Tue Sep 27 22:03:34 2011">
 Sep 27, 2011
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c4" href="/p/goagent/issues/detail?id=489#c4">#4</a>
 

 <a class="userlink"
 href="/u/107981847368000173475/">freedom8...@gmail.com</a
></span>
 
<pre>
什么东西更新到最新版？我的也是这个问题，不过只在mac下面有问题
</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc5">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Fri Apr  6 07:09:26 2012">
 Apr 6, 2012
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c5" href="/p/goagent/issues/detail?id=489#c5">#5</a>
 

 <a class="userlink"
 href="/u/101222008885129553701/">cumt.xia...@gmail.com</a
></span>
 
<pre>
我的1.8.0版也出现了相同的问题,请问该如何解决?
</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc6">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Wed Jul 18 05:41:51 2012">
 Jul 18, 2012
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c6" href="/p/goagent/issues/detail?id=489#c6">#6</a>
 

 <a class="userlink"
 href="/u/107937872856847585934/">Laurence...@gmail.com</a
></span>
 
<pre>
I'm getting an error the same as the subject line of this thread:
ssl.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

...and I'm looking for help trouble shooting. I can't follow any of the responses but the status reads fixed. Can anyone help?
</pre>
 
 
 </div>
 

 
 
 
 
 <div class="cursor_off vt issuecomment"
 id="hc7">
 <div style="float:right; margin-right:.3em; text-align:right">
 <span class="date" title="Wed Jul 18 05:41:52 2012">
 Jul 18, 2012
 </span>
 
 
 
 </div>
 
 
 
 
 
 
 
 
 
 
 <span class="author">
 
 <a name="c7" href="/p/goagent/issues/detail?id=489#c7">#7</a>
 

 <a class="userlink"
 href="/u/107937872856847585934/">Laurence...@gmail.com</a
></span>
 
<pre>
I'm getting an error the same as the subject line of this thread:
ssl.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

...and I'm looking for help trouble shooting. I can't follow any of the responses but the status reads fixed. Can anyone help?
</pre>
 
 
 </div>
 


 


 </td>
 </tr>

 
 <tr>
 <td></td>
 <td class="vt issuecomment">
 <span class="indicator">&#9658;</span> <a href="https://www.google.com/accounts/ServiceLogin?service=code&ltmpl=phosting&continue=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489&amp;followup=https%3A%2F%2Fcode.google.com%2Fp%2Fgoagent%2Fissues%2Fdetail%3Fid%3D489"
 >Sign in</a> to add a comment
 </td>
 </tr>
 

</tbody>
</table>
<br>
<script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/dit_scripts.js"></script>



 

</div> 
<form name="delcom" action="delComment.do?q=&amp;can=2&amp;groupby=&amp;sort=&amp;colspec=ID+Opened+Reporter+Modified+Summary+Stars" method="POST">
 <input type="hidden" name="sequence_num" value="">
 <input type="hidden" name="mode" value="">
 <input type="hidden" name="id" value="489">
 <input type="hidden" name="token" value="">
</form>

<div id="helparea"></div>
<script type="text/javascript">
 _onload();
 function delComment(sequence_num, delete_mode) {
 var f = document.forms["delcom"];
 f.sequence_num.value = sequence_num;
 f.mode.value = delete_mode;
 
 f.submit();
 return false;
 }
 
 _floatMetadata();
</script>
<script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/kibbles.js"></script>
<script type="text/javascript">
 _setupKibblesOnDetailPage(
 'https://code.google.com/p/goagent/issues/list?cursor\x3dgoagent%3A489',
 '/p/goagent/issues/entry',
 '',
 '',
 '', 'goagent', 489,
 false, false, codesite_token);
</script>
 
 
 
 <script type="text/javascript" src="https://ssl.gstatic.com/codesite/ph/8599073060794244502/js/ph_core.js"></script>
 
 
 
 
</div> 

<div id="footer" dir="ltr">
 <div class="text">
 <a href="/projecthosting/terms.html">Terms</a> -
 <a href="http://www.google.com/privacy.html">Privacy</a> -
 <a href="/p/support/">Project Hosting Help</a>
 </div>
</div>
 <div class="hostedBy" style="margin-top: -20px;">
 <span style="vertical-align: top;">Powered by <a href="http://code.google.com/projecthosting/">Google Project Hosting</a></span>
 </div>

 
 


 
 </body>
</html>

